import type { RecommendationKey } from '@/lib/analysisTypes'

export const CORPUS_DESCRIPTIONS: Record<RecommendationKey, string> = {
  color_complementary:     'Introduce a deliberate complementary accent: a single piece in the color opposite the dominant hue on the color wheel (e.g. blue outfit + burnt orange accessory). Limit to one complementary accent per outfit; overusing it creates clash instead of focus.',
  color_analogous:         'Build the palette from 2-3 hues that sit adjacent on the color wheel (e.g. blue + blue-green + green). Analogous palettes read as harmonious and effortless, but risk looking flat: introduce one textural or value contrast to add depth.',
  monochromatic_depth:     'Stay within a single hue but vary its value and saturation across pieces (e.g. navy blazer, mid-blue shirt, pale-blue pocket square). A high-quality monochromatic look can be more sophisticated than a multi-color outfit, provided the fit and texture work.',
  neutral_anchor:          'Ground the outfit with a neutral base (black, white, grey, beige, camel, navy, or olive). Neutrals do not count toward the three-color budget; they let accent colors and statement pieces breathe. Best when 60% or more of the visible area is neutral.',
  skin_tone_palette:       'Align palette temperature with the wearer skin undertone: warm undertones harmonize with earthy reds, oranges, yellows, camel and ivory; cool undertones harmonize with jewel tones, true blue, emerald, fuchsia and pure white. Place the most flattering tone near the face (collar, scarf, lapel) for maximum effect.',
  visual_balance_halves:   'Distribute visual weight between upper and lower body so neither half dominates. Pair a voluminous top (oversized knit, structured shoulders) with a slimmer bottom, or a wide-leg trouser with a closer-fitting top. The goal is equilibrium, not symmetry.',
  rule_of_thirds_outfit:   'Avoid splitting the silhouette in half. Aim for roughly 1/3 and 2/3 proportions between top and bottom (e.g. top covers 1/3 of the torso length, bottom 2/3, or vice versa for cropped styles). 50/50 splits tend to shorten the legs visually.',
  tuck_and_volume:         'When one piece is voluminous (wide trousers, full skirt, oversized jacket), tuck or half-tuck the more fitted piece to define the waist and prevent the silhouette from looking shapeless.',
  vertical_elongation:     'Use vertical visual lines to lengthen the silhouette: center-front buttons, vertical stripes, column of color, open jacket over a single-color layer, or a long necklace. One strong vertical line beats several weak ones.',
  pattern_scale_mix:       'When combining two or more patterns, ensure they are clearly different in scale: a large print paired with a micro print (e.g. wide plaid + small houndstooth). Similar-scale patterns compete and create visual noise.',
  texture_variety:         'Combine contrasting textures within the palette to add depth: matte with sheen, smooth with rough (e.g. wool + silk, denim + leather, knit + suede). One textural contrast is enough; stacking more dilutes the effect.',
  pattern_neutral_balance: 'Allow exactly one statement pattern to lead; all other pieces must read as solid, neutral, or low-contrast. The neutral pieces support, they do not compete. This is the safest way to wear a bold print.',
  tone_on_tone_texture:    'Stay within one color family but vary texture across pieces (e.g. camel cashmere + tan suede + chocolate leather). Tone-on-tone looks read as quiet luxury and rely on fit, fabric and texture to do the talking.',
  aesthetic_code_purity:   'Commit to one dominant aesthetic code (streetwear, formal, old money, grunge, athleisure, etc.) and let at least 80% of the pieces belong to it. A single bridge piece (accessory, shoe) may connect to a secondary code, but the dominant code must be unmistakable.',
  intentional_contrast:    'Mixing two aesthetic codes works only when the contrast is intentional and legible: anchor the look in code A (80%+ of pieces) and place one deliberate code-B piece as a statement. If the contrast could read as accidental, simplify. Context must allow the reading (editorial, creative industry, hybrid dress codes).',
  accessory_reinforcement: "Every accessory (shoes, belt, bag, watch, jewelry, headwear) must match the formality level and aesthetic code of the core outfit. Match shoe and belt in tone. The accessory either reinforces the dominant code or, if it intentionally breaks it, does so visibly and on purpose.",
  three_color_rule:        'Limit the outfit to three dominant colors at most. Neutrals (black, white, grey, beige, camel, denim) do not count toward the budget. One base color, one secondary color, one accent. More than three non-neutral colors creates saturation and visual fatigue.',
  fitted_relaxed_balance:  'Pair one fitted piece with one relaxed piece (e.g. fitted tee + relaxed trousers, or relaxed sweater + tailored pants). Two fitted pieces can read stiff; two relaxed pieces can read shapeless. The contrast creates form and movement.',
  waist_definition:        'Mark the waist, even in casual or oversized looks: tuck-in, half-tuck, belt at the natural waist, cropped top, or a seam that hits the narrowest point. A defined waist structures the silhouette regardless of body shape or style code.',
  hem_length_coordination: 'Coordinate hem lengths so they do not fragment the silhouette. A short jacket hitting the natural waist pairs with full-length trousers; a longer jacket at mid-thigh pairs with cropped or cuffed bottoms. Avoid two hems hitting the same awkward mid-zone.',
}
